const DETAILED_FIELDS = {
  galileo: {
    he: {
      summary: [
        "גלילאו גליליי היה מן הדמויות המרכזיות ביותר במהפכה המדעית של המאה השבע־עשרה. הוא שילב בין מתמטיקה, ניסוי, תצפית ומכשור מדעי, ובכך עזר לעצב את הדרך שבה המדע המודרני בודק את הטבע.",
        "חשיבותו אינה נובעת מתגלית אחת בלבד, אלא ממכלול של פעולות: שיפור הטלסקופ, הפנייתו אל השמים, פרסום ממצאים באופן ברור, והגנה נמרצת על הרעיון שהטבע צריך להיבחן באמצעות ראיות ולא רק באמצעות סמכות עתיקה.",
        "גלילאו הפך את התצפית האסטרונומית לחוויה משכנעת: הירח נראה הררי, השמש משתנה, צדק מוקף ירחים, ונוגה משנה מופעים. כל אלה ערערו את תמונת העולם הישנה וחיזקו את המודל ההליוצנטרי."
      ],
      discovery: [
        "הגילוי המרכזי של גלילאו היה למעשה אשכול של תצפיות טלסקופיות. בשנת 1610 הוא פרסם את Sidereus Nuncius, ובו תיאר בין היתר את ארבעת הירחים הגדולים של צדק. ירחים אלה הראו שקיימת מערכת שמימית קטנה שבה גופים מקיפים כוכב לכת אחר ולא את כדור הארץ.",
        "מופעי נוגה היו חשובים במיוחד משום שהם התאימו למודל שבו נוגה מקיף את השמש. אם נוגה עובר מופעים מלאים וחלקיים, הדבר קשה להסבר במסגרת גאוצנטרית פשוטה, אך טבעי יותר במערכת שבה השמש נמצאת במרכז תנועת הפלנטות.",
        "בנוסף, פני הירח וכתמי השמש ערערו את רעיון השמים המושלמים. השמים לא היו עוד תחום חלק, נצחי ובלתי משתנה, אלא אזור שבו קיימות צורות, תנועה ושינוי."
      ],
      impact: [
        "השפעת גלילאו הייתה מדעית, תרבותית ופילוסופית. הוא חיזק את ההליוצנטריות לא רק כמודל מתמטי אלא כתמונה ממשית של היקום. בעקבותיו נעשה קשה יותר להחזיק בתפיסה שכל גרמי השמים מקיפים את כדור הארץ.",
        "הוא גם תרם ליצירת דמותו של המדען המודרני: אדם שמודד, בודק, מפרסם ומתווכח על סמך ראיות. המדע נעשה פחות תלוי בפרשנות לספרים עתיקים ויותר תלוי בתצפיות חוזרות ובניסוח מתמטי.",
        "העימות שלו עם הכנסייה הפך לסמל היסטורי של המתח בין סמכות מוסדית לבין חקירה חופשית. גם אם המציאות ההיסטורית מורכבת יותר מן הסמל, השפעתו על דימוי המדע עצומה."
      ],
      etymology: [["Galileo / גלילאו", "שם איטלקי שמקורו בלטינית Galilaeus, כלומר אדם מן הגליל. השם קשור למסורת הנוצרית והלטינית, אך אצל גלילאו הוא מופיע כשם פרטי איטלקי."], ["Galilei / גליליי", "שם משפחה פלורנטיני. צורתו קשורה כנראה לשם Galileo עצמו ולשושלת משפחתית מקומית באיטליה של הרנסנס."], ["טלסקופ", "מן היוונית tele, רחוק, ו־skopein, להביט או להתבונן. כלומר: מכשיר לראיית דברים רחוקים."], ["הליוצנטרי", "מן היוונית helios, שמש, ו־kentron, מרכז. מודל שבו השמש משמשת כמרכז מערכת הפלנטות."], ["Sidereus Nuncius", "לטינית: 'השליח הכוכבי' או 'המסר מן הכוכבים'. זהו שם ספרו של גלילאו שבו פרסם את תצפיותיו הטלסקופיות הראשונות."]]
    },
    en: {
      summary: ["Galileo Galilei was one of the central figures of the seventeenth-century Scientific Revolution. He joined mathematics, experiment, observation, and scientific instruments, helping shape the modern way of investigating nature.", "His importance lies not in one discovery alone, but in a pattern of work: improving the telescope, turning it toward the heavens, publishing clear observations, and defending the idea that nature should be judged by evidence rather than ancient authority.", "Galileo made astronomical observation persuasive: the Moon appeared mountainous, the Sun changed, Jupiter had moons, and Venus showed phases. Together these findings undermined the older worldview and strengthened heliocentrism."],
      discovery: ["Galileo’s central discovery was a cluster of telescopic observations. In 1610 he published Sidereus Nuncius, describing, among other things, the four large moons of Jupiter. These moons showed that a smaller celestial system existed in which bodies orbited a planet other than Earth.", "The phases of Venus were especially important because they fit a model in which Venus orbits the Sun. Full and partial phases are difficult to explain in a simple geocentric system but natural in a Sun-centered planetary arrangement.", "The Moon’s surface and sunspots also challenged the idea of perfect heavens. The sky was no longer a smooth, eternal, unchanging realm, but a region of form, motion, and change."],
      impact: ["Galileo’s impact was scientific, cultural, and philosophical. He strengthened heliocentrism not merely as a mathematical model but as a physical picture of the universe.", "He also helped create the image of the modern scientist: someone who measures, tests, publishes, and argues from evidence. Science became less dependent on commentary on ancient books and more dependent on repeated observation and mathematical formulation.", "His conflict with the Church became a historical symbol of the tension between institutional authority and free inquiry. Even though the history is more complex than the symbol, its influence on the image of science is enormous."],
      etymology: [["Galileo", "Italian name from Latin Galilaeus, meaning a person from Galilee."], ["Galilei", "Florentine family name connected with the Galileo name and local Italian lineage."], ["Telescope", "From Greek tele, far, and skopein, to look: an instrument for seeing distant things."], ["Heliocentric", "From Greek helios, Sun, and kentron, center: a model centered on the Sun."], ["Sidereus Nuncius", "Latin for 'Starry Messenger' or 'message from the stars', Galileo’s early telescopic publication."]]
    }
  },
  copernicus: {
    he: {
      summary: ["ניקולאוס קופרניקוס היה אסטרונום ומתמטיקאי שהציע שינוי יסודי בתמונת היקום: כדור הארץ אינו המרכז הנייח שסביבו סובבים כל הגופים השמימיים, אלא פלנטה הנעה סביב השמש.", "החידוש שלו היה עמוק מפני שהוא נגע לא רק באסטרונומיה אלא גם בשאלת מקומו של האדם בעולם. אם הארץ אינה המרכז, גם האדם אינו נמצא עוד במרכז הפיזי של הבריאה.", "קופרניקוס לא פתר את כל בעיות האסטרונומיה, אך הוא פתח את הדלת למהפכה שהמשיכו קפלר, גלילאו וניוטון."],
      discovery: ["הגילוי המרכזי של קופרניקוס היה ניסוח המודל ההליוצנטרי: השמש קרובה למרכז המערכת, וכדור הארץ וכוכבי הלכת נעים סביבה.", "במודל זה כדור הארץ מבצע שתי תנועות חשובות: הוא מסתובב סביב צירו, ולכן אנו רואים יום ולילה, והוא מקיף את השמש, ולכן נוצרת שנת השמש. שינוי זה החליף את הרעיון שהשמים כולם מסתובבים סביב הארץ מדי יום.", "המודל פורסם בספר De revolutionibus orbium coelestium בשנת 1543, והפך לנקודת מוצא של אסטרונומיה חדשה, גם אם בתחילה התקבל בזהירות ובהתנגדות."],
      impact: ["השפעת קופרניקוס הייתה מהפכנית משום שהיא שינתה את מרכז התמונה. לא עוד עולם שבו הארץ היא ציר היקום, אלא מערכת שבה הארץ היא פלנטה אחת בתוך סדר קוסמי רחב.", "המודל שלו אפשר לקפלר לחשב מסלולים מדויקים יותר, לגלילאו לפרש תצפיות טלסקופיות, ולניוטון לנסח בהמשך חוק כבידה אוניברסלי.", "המונח 'מהפכה קופרניקאית' נעשה בהמשך סמל לכל שינוי מחשבתי שבו נקודת המבט הישנה מתהפכת מן היסוד."],
      etymology: [["Copernicus / קופרניקוס", "צורה לטינית של שם משפחה שמקורו כנראה בשם מקום בשלזיה, Koperniki. בתקופת הרנסנס היה מקובל ללטן שמות מלומדים."], ["Nicolaus / ניקולאוס", "צורה לטינית של Nicholas, מן היוונית Nike, ניצחון, ו־laos, עם: 'ניצחון העם'."], ["הליוצנטרי", "helios ביוונית הוא שמש, kentron הוא מרכז. כלומר: מודל שמשי־מרכזי."], ["De revolutionibus", "לטינית: 'על הסיבובים' או 'על המהפכות'. הכוונה לתנועות המחזוריות של הגופים השמימיים."], ["Orbium coelestium", "לטינית: 'של הספֵרות השמימיות' או 'של המסלולים השמימיים'."]]
    },
    en: {
      summary: ["Nicolaus Copernicus was an astronomer and mathematician who proposed a fundamental change in the picture of the universe: Earth is not the fixed center around which all heavenly bodies move, but a planet orbiting the Sun.", "His innovation was profound because it touched not only astronomy but humanity’s place in the world. If Earth is not the center, humankind is no longer physically central in creation.", "Copernicus did not solve every astronomical problem, but he opened the door to a revolution continued by Kepler, Galileo, and Newton."],
      discovery: ["Copernicus’ central discovery was the formulation of heliocentrism: the Sun lies near the center, and Earth and the planets move around it.", "In this model Earth has two crucial motions: it rotates on its axis, producing day and night, and it orbits the Sun, producing the year. This replaced the idea that the entire heavens rotate around Earth every day.", "The model appeared in De revolutionibus orbium coelestium in 1543 and became the starting point of a new astronomy, even if it was first received cautiously and sometimes with resistance."],
      impact: ["Copernicus’ impact was revolutionary because it changed the center of the picture. Earth was no longer the axis of the universe, but one planet within a broader cosmic order.", "His model enabled Kepler to calculate more accurate orbits, Galileo to interpret telescopic observations, and Newton to formulate universal gravitation.", "The phrase 'Copernican revolution' later became a symbol for any intellectual shift that overturns an older point of view."],
      etymology: [["Copernicus", "Latinized family name probably connected with the Silesian place-name Koperniki. Latinizing scholarly names was common in the Renaissance."], ["Nicolaus", "Latin form of Nicholas, from Greek nike, victory, and laos, people: 'victory of the people'."], ["Heliocentric", "From Greek helios, Sun, and kentron, center: Sun-centered."], ["De revolutionibus", "Latin: 'On the revolutions' or circular motions of heavenly bodies."], ["Orbium coelestium", "Latin: 'of the heavenly spheres' or celestial orbits."]]
    }
  },
  kepler: {
    he: {
      summary: ["יוהאנס קפלר היה אסטרונום ומתמטיקאי גרמני שהפך את המודל ההליוצנטרי למדויק הרבה יותר. הוא גילה שכוכבי הלכת אינם נעים במעגלים מושלמים, אלא במסלולים אליפטיים.", "עבודתו נשענה על הנתונים המדויקים של טיכו ברהה, אך דרשה גם אומץ מחשבתי: לוותר על אידיאל המעגל המושלם לטובת מה שהמדידות עצמן הראו.", "קפלר יצר גשר בין קופרניקוס לניוטון: הוא תיאר את חוקי התנועה הפלנטרית, וניוטון יסביר בהמשך מדוע החוקים האלה פועלים."],
      discovery: ["הגילוי המרכזי של קפלר הוא שלושת חוקי תנועת הפלנטות. החוק הראשון קובע שמסלולי הפלנטות הם אליפסות, והשמש נמצאת באחד ממוקדי האליפסה.", "החוק השני קובע שקו דמיוני בין הפלנטה לשמש מכסה שטחים שווים בזמנים שווים. משמעות הדבר היא שכוכב לכת נע מהר יותר כשהוא קרוב לשמש ולאט יותר כשהוא רחוק ממנה.", "החוק השלישי קובע יחס מתמטי בין זמן ההקפה של פלנטה לבין מרחקה מן השמש. בכך הפכה תנועת כוכבי הלכת לתופעה הניתנת לניסוח מספרי מדויק."],
      impact: ["השפעת קפלר הייתה עצומה: הוא הוציא את האסטרונומיה מן הצורך במעגלים מושלמים והכניס אותה לעידן שבו הנתונים קובעים את הצורה המתמטית של התאוריה.", "חוקיו סיפקו לניוטון חומר יסוד לניסוח חוק הכבידה. כאשר ניוטון הראה שהכבידה מסבירה את חוקי קפלר, נוצר חיבור אדיר בין אסטרונומיה לפיזיקה.", "קפלר גם הראה שמדע מתקדם כאשר מוכנים לשנות אידיאלים ישנים כדי להתאים למציאות הנמדדת."],
      etymology: [["Kepler / קפלר", "שם משפחה גרמני. מקורו המדויק אינו ודאי, אך הוא שייך לעולם השמות המקומיים והמקצועיים של גרמניה של ימי הביניים והעת החדשה המוקדמת."], ["Johannes / יוהאנס", "צורה לטינית־גרמנית של יוחנן, מן העברית 'יוחנן' — ה׳ חנן."], ["אליפסה", "מן היוונית elleipsis, חיסרון או השמטה. במתמטיקה זו עקומה סגורה בעלת שני מוקדים."], ["פלנטה", "מן היוונית planetes, נודד. כוכבי הלכת נקראו כך מפני שנראו נודדים על רקע כוכבי השבת."], ["אורביטה", "מן הלטינית orbita, מסלול או עקבה של גלגל. כיום: מסלול של גוף שמימי."]]
    },
    en: {
      summary: ["Johannes Kepler was a German astronomer and mathematician who made the heliocentric model far more precise. He discovered that planets do not move in perfect circles but in elliptical orbits.", "His work depended on Tycho Brahe’s accurate data but also required intellectual courage: abandoning the ideal of perfect circular motion in favor of what measurements actually showed.", "Kepler formed a bridge between Copernicus and Newton: he described the laws of planetary motion, and Newton later explained why those laws work."],
      discovery: ["Kepler’s central discovery is the three laws of planetary motion. The first law states that planetary orbits are ellipses, with the Sun at one focus.", "The second law states that a line between a planet and the Sun sweeps out equal areas in equal times. This means a planet moves faster near the Sun and slower when farther away.", "The third law gives a mathematical relation between a planet’s orbital period and its distance from the Sun, making planetary motion precisely numerical."],
      impact: ["Kepler’s impact was enormous: he moved astronomy away from the demand for perfect circles and into an era in which data determines the mathematical form of theory.", "His laws provided Newton with essential material for the law of gravitation. When Newton showed that gravity explains Kepler’s laws, astronomy and physics were powerfully joined.", "Kepler also showed that science advances when old ideals are changed to fit measured reality."],
      etymology: [["Kepler", "German surname of uncertain origin, belonging to the world of local and occupational names in German-speaking Europe."], ["Johannes", "Latin-German form of John, from Hebrew Yohanan: 'God has been gracious'."], ["Ellipse", "From Greek elleipsis, omission or falling short; a closed curve with two foci."], ["Planet", "From Greek planetes, wanderer, because planets appear to wander against the fixed stars."], ["Orbit", "From Latin orbita, track or wheel-rut; today, the path of a celestial body."]]
    }
  },
  tycho: {
    he: {
      summary: ["טיכו ברהה היה האסטרונום התצפיתי הגדול ביותר שלפני עידן הטלסקופ. חשיבותו נובעת לא מתאוריה אחת מפורסמת, אלא מיצירת מאגר מדידות מדויק באופן חסר תקדים.", "הוא בנה מכשירי מדידה גדולים, הקים את מצפה אורניבורג, ויצר סביבו מוסד מחקר מוקדם שבו נאספו תצפיות לאורך שנים.", "הנתונים של טיכו היו הבסיס שעליו קפלר גילה את חוקי תנועת הפלנטות."],
      discovery: ["תצפיותיו המרכזיות כללו מדידות מדויקות של כוכבים וכוכבי לכת, תיעוד הסופרנובה של 1572 ותצפית בשביט של 1577.", "הסופרנובה הראתה כי שינוי יכול להתרחש גם בשמים הרחוקים, בניגוד לתפיסה שהשמיים העליונים נצחיים ובלתי משתנים.", "השביט של 1577 סייע להראות שתופעות כאלה אינן בהכרח אירועים אטמוספריים קרובים, אלא עשויות להיות חלק מן המרחב השמימי עצמו."],
      impact: ["טיכו שינה את מעמד הנתונים במדע. הוא הראה שתאוריה אסטרונומית טובה חייבת להישען על מדידות שיטתיות ומדויקות.", "ללא המדידות שלו, קפלר לא היה יכול להגיע באותה דרך לחוקי המסלולים האליפטיים. לכן טיכו הוא חלק הכרחי בשרשרת המובילה מקופרניקוס לניוטון.", "הוא גם ערער את ההבחנה הישנה בין עולם ארצי משתנה לבין שמים מושלמים וקבועים."],
      etymology: [["Tycho / טיכו", "צורה לטינית של השם הדני Tyge. השימוש בצורה לטינית היה נפוץ בקרב מלומדי אירופה."], ["Brahe / ברהה", "שם משפחת אצולה דני־שוודי. מעמדו החברתי של טיכו היה מרכזי ביכולתו לבנות מצפה ומפעל מדעי."], ["Uraniborg / אורניבורג", "שם המצפה שבנה טיכו. Urania היא מוזת האסטרונומיה במיתולוגיה היוונית, borg בשפות סקנדינביות פירושו טירה או מבצר."], ["סופרנובה", "מלטינית nova, חדשה. הכוונה לכוכב שנראה לפתע כ'כוכב חדש', אף שמדובר באירוע אסטרופיזיקלי של כוכב קיים."], ["קומטה / שביט", "מן היוונית kometes, בעל שיער, בשל המראה של זנב השביט."]]
    },
    en: {
      summary: ["Tycho Brahe was the greatest observational astronomer before the telescope. His importance lies not in one famous theory but in creating an unprecedented body of accurate measurements.", "He built large measuring instruments, founded the observatory Uraniborg, and created an early research institution where observations were collected over many years.", "Tycho’s data became the foundation on which Kepler discovered the laws of planetary motion."],
      discovery: ["His central observations included precise measurements of stars and planets, the supernova of 1572, and the comet of 1577.", "The supernova showed that change could occur in the distant heavens, contrary to the idea that the upper heavens were eternal and unchanging.", "The comet of 1577 helped show that such phenomena were not necessarily nearby atmospheric events but could belong to celestial space itself."],
      impact: ["Tycho changed the status of data in science. He showed that good astronomical theory must rest on systematic and precise measurement.", "Without his measurements, Kepler could not have reached the laws of elliptical orbits in the same way. Tycho is therefore an essential link from Copernicus to Newton.", "He also weakened the old distinction between a changing earthly world and perfect, fixed heavens."],
      etymology: [["Tycho", "Latin form of the Danish name Tyge, reflecting the Latin scholarly style of Europe."], ["Brahe", "Danish-Swedish noble family name; his social rank was central to his scientific resources."], ["Uraniborg", "Name of Tycho’s observatory: Urania was the Greek muse of astronomy, and borg means castle or fortress in Scandinavian languages."], ["Supernova", "From Latin nova, new; a star that appears suddenly as a 'new star'."], ["Comet", "From Greek kometes, hairy, referring to the comet’s tail."]]
    }
  }
};

for (const scientist of SCIENTISTS) {
  const detailed = DETAILED_FIELDS[scientist.id];
  if (!detailed) continue;
  for (const langKey of ["he", "en"]) {
    if (detailed[langKey]) Object.assign(scientist[langKey], detailed[langKey]);
  }
}
